#!/bin/bash

echo "🤖 Welcome to Archie Setup!"
echo "=========================================="
echo ""
echo "Archie supports both OpenAI and Claude AI providers."
echo "You need at least ONE API key to get started."
echo ""
echo "📝 Where to get API keys:"
echo "  • OpenAI: https://platform.openai.com/api-keys"
echo "  • Claude: https://console.anthropic.com/"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists!"
    read -p "Do you want to overwrite it? (y/n): " overwrite
    if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
        echo "Setup cancelled. Your existing .env file is unchanged."
        exit 0
    fi
    echo ""
fi

# Prompt for OpenAI API key
echo "=========================================="
echo "OPENAI CONFIGURATION"
echo "=========================================="
echo ""
read -p "Enter your OpenAI API Key (or press Enter to skip): " openai_key
echo ""

# Prompt for Claude API key
echo "=========================================="
echo "CLAUDE CONFIGURATION"
echo "=========================================="
echo ""
read -p "Enter your Claude API Key (or press Enter to skip): " claude_key
echo ""

# Validate that at least one key was provided
if [ -z "$openai_key" ] && [ -z "$claude_key" ]; then
    echo "❌ Error: You must provide at least ONE API key (OpenAI or Claude)."
    echo ""
    echo "Run this script again and enter at least one API key."
    exit 1
fi

# Create .env file
echo "Creating .env file..."
cat > .env << EOF
# Archie - AI Tech Co-Founder Configuration
# Auto-generated by setup.sh

# ==============================================
# AI PROVIDER API KEYS
# ==============================================

# OpenAI API Key
OPENAI_API_KEY=$openai_key

# Claude API Key
ANTHROPIC_API_KEY=$claude_key

# ==============================================
# OPTIONAL: AI MODEL CONFIGURATION
# ==============================================

# OpenAI Model (default: gpt-4-turbo-preview)
OPENAI_MODEL=gpt-4-turbo-preview

# Claude Model (default: claude-sonnet-4-20250514)
CLAUDE_MODEL=claude-sonnet-4-20250514

# ==============================================
# SERVER CONFIGURATION
# ==============================================

PORT=3000
EOF

echo ""
echo "✅ Setup complete!"
echo "=========================================="
echo ""

# Show what was configured
if [ -n "$openai_key" ] && [ -n "$claude_key" ]; then
    echo "🎉 BOTH providers configured!"
    echo "   Mode: PARALLEL COMPARISON (best quality)"
    echo "   Archie will call both OpenAI and Claude, then return the best result."
elif [ -n "$openai_key" ]; then
    echo "✅ OpenAI configured"
    echo "   Mode: OpenAI only"
    echo "   💡 Tip: Add a Claude key later for parallel comparison mode."
elif [ -n "$claude_key" ]; then
    echo "✅ Claude configured"
    echo "   Mode: Claude only (best quality)"
    echo "   💡 Tip: Add an OpenAI key later for parallel comparison mode."
fi

echo ""
echo "=========================================="
echo "NEXT STEPS"
echo "=========================================="
echo ""
echo "1. Start the server:"
echo "   npm start"
echo ""
echo "2. Open your browser:"
echo "   http://localhost:3000"
echo ""
echo "3. (Optional) Test your setup:"
echo "   npm test"
echo ""
echo "=========================================="
echo ""
echo "Need help? Check SETUP.md for detailed instructions."
echo ""
